### ISSUE TITLE
Ability to change the port for Rest

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-rest#109]
## Issue

Changing the Rest port is not possible. The server launches, but the commands related to Taipy Rest give a 404 response. It should also be documented how to change the Rest port.

## How to replicate

- Create entities and start a Rest instance with a different port.

```python
from taipy.config import Config
import taipy as tp

def f(i):
    return i

d1_cfg = Config.configure_data_node('d1', default_data=1)
d2_cfg = Config.configure_data_node('d2')
task_cfg = Config.configure_task(id="task", function=f, input=d1_cfg, output=d2_cfg)
s = Config.configure_scenario_from_tasks('s', [task_cfg])

if __name__ == "__main__":

    rest_port = 5005  # Change this to the desired port number
    tp.Rest().run(port=rest_port)
```

## Expected behavior

Changing the port of the Rest server should be possible.
It should be documented as well.

## Screenshot

![image (2)](https://github.com/Avaiga/taipy-rest/assets/98709993/6f43ec81-5dd6-4323-ba3f-91fd556a3cfb)

**Comment by joaoandre-avaiga** [comment]
Hi! The port change does work. As you mentioned, you can access the URL on the new port and you receive a 404 for  the home url `localhost:5005/`, which is expected, if I'm not mistaken we don't have a page for this URL on rest. If you try however, to list the scenarios on the URL `http://localhost:5005/api/v1/scenarios` you will see that it returns 200 with the list of scenarios, or an empty list if nothing was created.
![Screen Shot 2023-08-01 at 22.23.40.png](https://images.zenhubusercontent.com/613f36b9de2b3fa7094201b7/2147f54f-014d-4f59-b414-95d19bc7616a)
![Screen Shot 2023-08-01 at 22.23.51.png](https://images.zenhubusercontent.com/613f36b9de2b3fa7094201b7/96d8433b-400d-4909-8bef-1f2d66ecc0cd)

**Comment by joaoandre-avaiga** [comment]
Can you try it on your end and let me know?

In any case, this should be added to the documentation as you suggested.
