### ISSUE TITLE
Upgrade Flask to the latest version

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-rest#131]
Dependabot complains about the version of Flask we are using in Taipy GUI.
The plan is to upgrade it at least to the latest minor version (2.3 as of today).

We, of course, want to have GUI and REST aligned on this matter.

**Comment by trgiangdo** [comment]
After flask is upgraded on taipy-gui, the installation test on taipy is failing
```
ERROR: Cannot install taipy because these package versions have conflicting dependencies.

The conflict is caused by:
    taipy-gui 3.0.0.dev2 depends on flask<2.4 and >=2.3.3
    taipy-rest 3.0.0.dev3 depends on flask<2.3 and >=2.2
```
