### ISSUE TITLE
Allow to run tests after installation of taipy

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy-rest#41]
The REST package looks like this:
```
- src
  - taipy
    - rest
- tests
```

Some _tests_ depend on _import_ based on the _src.taipy_. This is a problem when we want to test if the package is correctly installed from _pypi_ because we removed the _src_ folder to ensure we are testing the package install by _pypi_ and not the local.

** Acceptance criteria **
We should be able to do:
```
cd taipy-rest
pip install .
rm -r src
pytest
```

**Comment by jrobinAV** [comment]
OBSOLETE
